#!/usr/bin/env python3
# What this does: builds the label hierarchy, name-map, and checks for lack of label in the image inventory.
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(r"D:\Pollen\pollen_project")
TAX = PROJECT_ROOT / "outputs" / "taxonomy"
INV = PROJECT_ROOT / "outputs" / "inventory" / "master_inventory.csv"
REVIEWED_CSV = TAX / "taxonomy_lookup_reviewed.csv"
HIER_CSV = TAX / "taxonomy_hierarchy.csv"
HIER_PY = TAX / "taxonomy_hierarchy.py"
ORPHAN_CSV = TAX / "orphan_report.csv"


def main():
# Build the label hierarchy, name-map and run label check
    if not REVIEWED_CSV.exists():
        raise SystemExit(f"Missing {REVIEWED_CSV}. Run phase1.2.3_apply_review.py first.")
    rev = pd.read_csv(REVIEWED_CSV, dtype=str, keep_default_na=False)

    kept = rev[rev["final_label"] != ""].copy()
    excluded = set(rev[rev["final_label"] == ""]["genus_raw"])

    hier = kept[["genus_raw", "final_label", "label_rank",
                 "accepted_genus", "family"]].rename(
        columns={"genus_raw": "original_label"})
    hier = hier.sort_values(["final_label", "original_label"])
    hier.to_csv(HIER_CSV, index=False, encoding="utf-8")

    label_map = dict(zip(kept["genus_raw"], kept["final_label"]))

# Write .py file for the name-map
    lines = ['"""Auto-generated by phase1.2.4. raw label -> final class label."""',
             "", "LABEL_MAP = {"]
    for k in sorted(label_map):
        lines.append(f"    {k!r}: {label_map[k]!r},")
    lines.append("}")
    lines.append("")
    lines.append("EXCLUDED = {")
    for k in sorted(excluded):
        lines.append(f"    {k!r},")
    lines.append("}")
    lines.append("")
    HIER_PY.write_text("\n".join(lines), encoding="utf-8")

# Check inventory labels
    orphans = pd.DataFrame()
    if INV.exists():
        inv = pd.read_csv(INV, low_memory=False, usecols=["genus"])
        inv_genera = set(inv["genus"].dropna().astype(str).str.strip()) - {""}
        mapped = set(label_map)
        unmapped = sorted(g for g in inv_genera if g not in mapped and g not in excluded)
        orphans = pd.DataFrame({"inventory_label": unmapped})
        orphans.to_csv(ORPHAN_CSV, index=False, encoding="utf-8")

# Printed summary
    n_genus = (kept.label_rank == "genus").sum()
    n_family = (kept.label_rank == "family").sum()
    print(f"hierarchy rows (kept labels): {len(hier):,}")
    print(f"  -> genus-level labels      : {n_genus:,}")
    print(f"  -> family-level labels     : {n_family:,}")
    print(f"  distinct final classes     : {kept['final_label'].nunique():,}")
    print(f"  excluded labels            : {len(excluded):,}")
    print(f"\n  written: {HIER_CSV.name}, {HIER_PY.name}")
    if INV.exists():
        if len(orphans):
            print(f"\n  ⚠ ORPHANS: {len(orphans)} inventory labels map to nothing "
                  f"and were not excluded — see {ORPHAN_CSV.name}")
            print("    (investigate before Phase 1.3 — these images would be unlabelled)")
        else:
            print(f"\n  orphan check: PASS — every inventory label maps or is excluded.")
    else:
        print(f"\n  (inventory not found at {INV} — skipped orphan check)")


if __name__ == "__main__":
    main()
